package spass;

import java.util.EventObject;

/**
 * Represents a number-related event,
 * generated by a <code>NumberField</code>.
 * 
 * @author Oliver Eickmeyer
 */
@SuppressWarnings("serial")
public class NumberEvent extends EventObject{

	/**
	 * Constructs a new event, generated by a <code>NumberField</code>.
	 * @param source the <code>NumberField</code> generating this event
	 */
	public NumberEvent(Object source) {
		super(source);
	}

}
